# Generated by Django 4.2.4 on 2023-08-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('gender', models.CharField(choices=[['Male', 'Male'], ['Female', 'Female']], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('desc', models.TextField(max_length=500)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('profile_resume', models.FileField(upload_to='profile_resume/')),
            ],
        ),
    ]
